version: '3'
services:
  slave-1:
    image: duck-meter
    volumes:
      - ./jmeter_home:/mnt/jmeter
    command: -s -n -Jserver.rmi.localport=60000 -j /mnt/jmeter/jlogs/slave1.log
  slave-2:
    image: duck-meter
    volumes:
      - ./jmeter_home:/mnt/jmeter
    command: -s -n -Jserver.rmi.localport=60000 -j /mnt/jmeter/jlogs/slave2.log
  slave-3:
    image: duck-meter
    volumes:
      - ./jmeter_home:/mnt/jmeter
    command: -s -n -Jserver.rmi.localport=60000 -j /mnt/jmeter/jlogs/slave3.log
  master:
    image: duck-meter
    volumes:
      - ./jmeter_home:/mnt/jmeter
    depends_on:
      - slave-1
      - slave-2
      - slave-3
      - rubber-duck-1
    environment:
      - DISPLAY=host.docker.internal:0
    command: >
      -t /mnt/jmeter/test_rubber_duck.jmx \
      -Jremote_hosts=slave-1,slave-2,slave-3 \
      -Dremote.x11.workaround=false \
      -Dawt.useSystemAAFontSettings=lcd \
      -Dsun.java2d.renderer=sun.java2d.marlin.MarlinRenderingEngine \
      -Djava2d.font.loadFontConf=true \
      -Dsun.java2d.xrender=false
      -j /mnt/jmeter/jlogs/master.log
  rubber-duck-1:
    image: rubber-duck
networks:
  jmeter_cluster: {}
